version: '3.8'

name: prisma-timezone-report
services:
  mysql:
    image: mysql:8.0.36
    container_name: ${COMPOSE_PROJECT_NAME}_mysql
    ports:
      - 127.0.0.1:${DATABASE_PORT:-33066}:3306
    environment:
      MYSQL_DATABASE: ${DATABSE_NAME:-$COMPOSE_PROJECT_NAME}
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD:-ptrpass}'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default_authentication_plugin=mysql_native_password --skip-log-bin --log-error-verbosity=1  --default-time-zone=Asia/Tokyo
    volumes:
      - .mysql/data:/var/lib/mysql
    networks:
      - ${COMPOSE_PROJECT_NAME}_network
networks:
  ${COMPOSE_PROJECT_NAME}_network:
